android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
project.android.compileSdk=37
project.android.minSdk=26
project.android.targetSdk=35
project.module-app.packageName=com.via.whitelistbypass
project.module-app.versionName=3.2.0
project.module-app.versionCode=10029
android.aapt2FromMavenOverride=/workspace/tools/android-sdk/build-tools/37.0.0/aapt2
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-arm64
