plugins {
    id 'com.android.application'
}

android {
    namespace = 'com.via.whitelistbypass'
    compileSdk = 37

    signingConfigs {
        create("universal") {
            keyAlias = "androiddebugkey"
            keyPassword = "android"
            storeFile = file("../debug.keystore")
            storePassword = "android"
        }
    }
    defaultConfig {
        applicationId = "com.via.whitelistbypass"
        minSdk = 26
        targetSdk = 35
        versionName = "3.2.0"
        versionCode = 10030
    }
    buildTypes {
        all { signingConfig = signingConfigs.getByName("universal") }
        debug {
            debuggable = true
        }
        release {
            minifyEnabled = false
            debuggable = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig true
    }
    lint { checkReleaseBuilds = false }
}

dependencies {
    compileOnly(files("libs/libxposed/api.jar"))
    implementation(files("libs/libxposed/interface.jar"))
    implementation(files("libs/libxposed/service.jar"))
    implementation(files("libs/pinyin4j-2.5.1.jar"))
}
